version: '3.5'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      # - ./addons:/mnt/extra-addons
      - ./custom:/custom
      - ./odoo-log-data:/var/log/odoo
      - /data/.key:/data/.key
      - /Users/kkday/Documents/Work/Github_Codes/kk_lib_code/py_lib/library_ver3:/custom/library_ver3
    # command:
    #   odoo -r odoo -w odoo -i addons -d odoo
  db:
    image: postgres:10.9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
